#!/bin/bash

IMP="OMP"

for I in {1..24} ; do
	for J in {0..9} ; do
		{ time -p ../../run -nb_threads $I -from C1 -to C100 -departure_time_min 00000000100000 -departure_time_max 00000000450000 -arrival_time_min 00000000550000 -arrival_time_max 00000000900000 -max_layover 1000 -vacation_time_min 50000 -vacation_time_max 200000 -flights flights.txt -alliances alliances.txt -work_hard_file work_hard.txt -play_hard_file play_hard.txt -vacation_airports C{2..51}  ; } 2>&1 | awk "BEGIN { WALL=\"\" ; USER=\"\"; } { if(\$1 == \"real\") WALL=\$2 ; if(\$1 == \"user\") USER=\$2 } END { print \"$IMP;$I;\" WALL \";\" USER \";\" (USER/WALL) }" >> intel-benchmark-13-$(date +%s).csv
	done
done
